//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTService.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEGDEPWEntities : DbContext
    {
        public SEGDEPWEntities()
            : base("name=SEGDEPWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asistenciaEntrenamientos> asistenciaEntrenamientos { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<categoriasPersonas> categoriasPersonas { get; set; }
        public virtual DbSet<climas> climas { get; set; }
        public virtual DbSet<clubes> clubes { get; set; }
        public virtual DbSet<destrezas> destrezas { get; set; }
        public virtual DbSet<destrezasGrupos> destrezasGrupos { get; set; }
        public virtual DbSet<destrezasNiveles> destrezasNiveles { get; set; }
        public virtual DbSet<destrezasPersonas> destrezasPersonas { get; set; }
        public virtual DbSet<entrenadores> entrenadores { get; set; }
        public virtual DbSet<entrenamientos> entrenamientos { get; set; }
        public virtual DbSet<estadoCampos> estadoCampos { get; set; }
        public virtual DbSet<eventos> eventos { get; set; }
        public virtual DbSet<jugadores> jugadores { get; set; }
        public virtual DbSet<localidades> localidades { get; set; }
        public virtual DbSet<lugares> lugares { get; set; }
        public virtual DbSet<medidas> medidas { get; set; }
        public virtual DbSet<pagos> pagos { get; set; }
        public virtual DbSet<pagoTipos> pagoTipos { get; set; }
        public virtual DbSet<partidos> partidos { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<posiciones> posiciones { get; set; }
        public virtual DbSet<posicionesPersonas> posicionesPersonas { get; set; }
        public virtual DbSet<situaciones> situaciones { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<temporadas> temporadas { get; set; }
        public virtual DbSet<tipoDocumentos> tipoDocumentos { get; set; }
        public virtual DbSet<tipoEntrenador> tipoEntrenador { get; set; }
        public virtual DbSet<tipoPersonas> tipoPersonas { get; set; }
        public virtual DbSet<tipoSesion> tipoSesion { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<valores> valores { get; set; }
        public virtual DbSet<variables> variables { get; set; }
    }
}
