//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class destrezas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public destrezas()
        {
            this.destrezasPersonas = new HashSet<destrezasPersonas>();
        }
    
        public int ID { get; set; }
        public string deno { get; set; }
        public int idNivel { get; set; }
        public int idGrupo { get; set; }
        public string nota { get; set; }
        public Nullable<int> idusuariomod { get; set; }
        public Nullable<System.DateTimeOffset> fechamod { get; set; }
    
        public virtual destrezasGrupos destrezasGrupos { get; set; }
        public virtual destrezasNiveles destrezasNiveles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<destrezasPersonas> destrezasPersonas { get; set; }
    }
}
