//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos
    {
        public int ID { get; set; }
        public System.DateTimeOffset hora { get; set; }
        public int idsituacion { get; set; }
        public int idpartido { get; set; }
        public int idpersona { get; set; }
        public int idcategoria { get; set; }
        public int idvariable { get; set; }
        public int idlugar { get; set; }
        public Nullable<int> idusuariomod { get; set; }
        public Nullable<System.DateTimeOffset> fechamod { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual lugares lugares { get; set; }
        public virtual partidos partidos { get; set; }
        public virtual personas personas { get; set; }
        public virtual situaciones situaciones { get; set; }
        public virtual variables variables { get; set; }
    }
}
