//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public int ID { get; set; }
        public int idPagoTipos { get; set; }
        public int idPersona { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string mesimputar { get; set; }
        public Nullable<int> idusuariomod { get; set; }
        public Nullable<System.DateTimeOffset> fechamod { get; set; }
    
        public virtual pagoTipos pagoTipos { get; set; }
        public virtual personas personas { get; set; }
    }
}
