//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class salud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salud()
        {
            this.saludenfermedades = new HashSet<saludenfermedades>();
        }
    
        public int ID { get; set; }
        public int idpersona { get; set; }
        public int idcategoria { get; set; }
        public string altura { get; set; }
        public string peso { get; set; }
        public string torg { get; set; }
        public string sangregrupo { get; set; }
        public string sangrefactor { get; set; }
        public string nota { get; set; }
        public Nullable<int> idusuariomod { get; set; }
        public Nullable<System.DateTimeOffset> fechamod { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual personas personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saludenfermedades> saludenfermedades { get; set; }
    }
}
